export const FETCH_DATA_REQUEST="FETCH_DATA_REQUEST";
export const FETCH_DATA_SUCCESS="FETCH_DATA_SUCCESS";
export const FETCH_DATA_FAILURE="FETCH_DATA_FAILURE";


export const FETCH_PRODUCT_REQUEST="FETCH_PRODUCT_REQUEST";
export const FETCH_PRODUCT_SUCCESS="FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE="FETCH_PRODUCT_FAILURE";


export const SIGN_IN_REQUEST="SIGN_IN_REQUEST";
export const SIGN_IN_SUCCESS="SIGN_IN_SUCCESS";
export const SIGN_IN_FAILURE="SIGN_IN_FAILURE";


export const ADD_CART_REQUEST="ADD_CART_REQUEST";
export const ADD_CART_SUCCESS="ADD_CART_SUCCESS";
export const ADD_CART_FAILURE="ADD_CART_FAILURE";



export const GET_CART_REQUEST="GET_CART_REQUEST";
export const GET_CART_SUCCESS="GET_CART_SUCCESS";
export const GET_CART_FAILURE="GET_CART_FAILURE";


export const IsAuth = "IsAuth";